### ISSUE TITLE
Question: UIScrollView to grow dynamically while adding views at runtime

### ISSUE THREAD

**Issue by ghost** [smileyborg/UIView-AutoLayout#13]
Hey smileyborg,

First of all, congrats for your efforts developing UIView-AutoLayout. A very sincere THANK YOU!

My question is about a UIScrollView. I'm trying to do something like the Facebook Timeline, but I don't want to use UITableView in order to learn AutoLayout and also to have more freedom to customize.

I want to put an empty UIScrollView in a View Controller and, in runtime, I will add subviews with dynamic heights, but the scroll view never gets the correct contentSize height.
- Which constraints would you suggest me to add?
- Is it necessary to add Vertical Space from every added View's bottom to Scroll View bottom?

After days trying to solve these issue, I'm wondering if AutoLayout is really ready for being used purely without frames.

I appreciate your help. Thanks in advance.

**Comment by lluissm** [comment]
You need to setup all the vertical constraints. 

Top to first view, between views, last view to bottom.

**Comment by ghost** [comment]
Hi lluis-lsm,

Thanks for your reply. I'm gonna try to implement this way. I come back to
thank you or to ask for more help.

I swear that I am not asking before reading a lot and trying. Most people
ask when they are lazy. :)

Em sábado, 10 de maio de 2014, lluis-lsm notifications@github.com
escreveu:

**Comment by ghost** [comment]
Hey,

Should I remove the vertical space constraint (the one with 500 constant) when I add a new button? If so, what would be the constant I should put? :-( I have no idea on how I can calculate this constant without checking frames, contentSize...

Another problem is that IB requires that I add a Width constraint to button, this means I can't support landscape orientations without some "magic numbers" in code... :-1: 

![shot](https://cloud.githubusercontent.com/assets/7061696/2937050/27f734de-d883-11e3-8ab7-1162f087a1dc.png)

Thanks

**Comment by smileyborg** [comment]
First of all, make sure you are aware of this Technical Note: https://developer.apple.com/LIBRARY/ios/technotes/tn2154/_index.html

I haven't tried doing exactly what you're doing myself. But I would use the 'Mixed Approach' Apple recommends in their technical note above.

That would mean, you create a plain container UIView that doesn't use Auto Layout (`translatesAutoresizingMaskIntoConstraints = NO`), then to this container view you add each of your dynamic-height subviews. Then, you add constraints to hook up each of these dynamic height subviews to one another vertically, with the top one connected to the top of the container view, and the bottom one connected to the bottom of the container view. (**Don't** connect the middle subviews with vertical constraints to the container view!)

Next, you need to do basically what you would for a [table view cell using Auto Layout](http://stackoverflow.com/questions/18746929/using-auto-layout-in-uitableview-for-dynamic-cell-layouts-variable-row-heights) -- make sure all the content is set, then force the container UIView to layout, then call `systemLayoutSizeFittingSize:` on it to find out how big it wants to be. Once you get this height, you set the container view's `bounds.size.height` to this value.

Finally, (if not already done) add this container view as the one subview of the UIScrollView, and set the scroll view's `contentSize` to match the size of this container view.

If your content changes, you should basically just need to update the views with the new content, re-calculate the new height, and then update the frame of the container view & contentSize of the scroll view as needed.

Does that make sense?

**Comment by smileyborg** [comment]
By the way, in the horizontal dimension you wouldn't want to set fixed widths for anything - instead, you would pin the subviews to the left & right edges of the container view, and then before you do the layout calculation to get the height, just set the container view's width to be fixed at whatever the scroll view's width is in the current orientation of the device.

**Comment by ghost** [comment]
Terrific, Tyler! Your recommendation about the mixed approach gives me some
relief. O thought I would be cheating by using it. LOL

If you don't mind, I'll consider a donation in a near future for your great
work. : )

Cheers from Brazil

Em sábado, 10 de maio de 2014, Tyler Fox notifications@github.com
escreveu:

**Comment by lluissm** [comment]
Superb explanation.

**Comment by ghost** [comment]
Yeah, I give it up for now to meet my deadline. I'm "officially too stupid for AutoLayout with UIScrollView". It seems that only Apple can do the magic of a UITableView. I'll resume the research as soon as I finish this project. Thanks anyway.

**Comment by ghost** [comment]
BTW, in the meantime, I'll do with a UITableView...

**Comment by smileyborg** [comment]
OK sounds good. If you do get around to implementing this, I think it would be really useful for people to have a sample project on GitHub that they could reference. I'd be happy to post the link around.

I'm going to close this issue for now but feel free to comment here or open a new one if needed.

**Comment by ghost** [comment]
Alright! I'll manage to do that. Thanks!

**Comment by Cynthia-Cao2025** [comment]
Hi @hiramgeeks ,
How did you implement this part: UIScrollView to grow dynamically while adding views at runtime? I really appreciate your help. I have been working on this part for several days.

**Comment by ghost** [comment]
Hi AmyCao,

As far as I can recall, I needed to use UITableView to resolve this
problem. At that time, with the dead line approaching, I gave up
implementing the solution from scratch by myself.

These things should be a lot easier to do. The API should provide more
ready-to-use resources for a so common problem.

I would tell you to look for cocoapods and Cocoa controls. There must have
an open source solution for this problem (at least partially) there.
Em 12/07/2015 02:21, "AmyCao" notifications@github.com escreveu:

**Comment by terrymichel** [comment]
Hi, 

I can of dig out an old post but here is an implementation of an [HorizontalScrollView using auto layout](https://github.com/TerryMichel/HorizontalScrollViewAutoLayout) if this can help anyone ;)

**Comment by mgregor** [comment]
Terry's solution was spot on and a lot less complicated that some other solutions I have seen posted!  Thanks Terry!!
