### ISSUE TITLE
About the ALAxis descriptions

### ISSUE THREAD

**Issue by qunten** [smileyborg/UIView-AutoLayout#14]
I couldn't quite understand why using `NSLayoutAttributeCenterX` to describe `ALAxisVertical`, why not use NSLayoutAttributeCenterY instead?

**Comment by smileyborg** [comment]
Did you see the comment [here where the constant is defined](https://github.com/smileyborg/UIView-AutoLayout/blob/master/Source/UIView%2BAutoLayout.h#L49)?

Perhaps a picture will clarify better:

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313337323535372f313635323837352f39353130303166612d356232332d313165332d393162622d3436313333386537343761652e706e67](https://cloud.githubusercontent.com/assets/1372557/3009849/66b897da-df09-11e3-810e-0d7f487fa66e.png)

I promise that it is quite intuitive and consistent when you understand how it's defined!
