### ISSUE TITLE
Probably wrong axis attribute

### ISSUE THREAD

**Issue by zhjuncai** [smileyborg/UIView-AutoLayout#16]
```
typedef NS_ENUM(NSInteger, ALAxis) {
    ALAxisVertical = NSLayoutAttributeCenterX,      // a vertical line through the center of the view
    ALAxisHorizontal = NSLayoutAttributeCenterY,    // a horizontal line through the center of the view
    ALAxisBaseline = NSLayoutAttributeBaseline      // a horizontal line at the text baseline (not applicable to all views)
};
```

In the header file, `ALAxisVertical = NSLayoutAttributeCenterX,`  is that correct, I think it suppose to be ALAxisVertical = NSLayoutAttributeCenterY,

**Comment by zhjuncai** [comment]
I pretty sure it's a small mistake

**Comment by smileyborg** [comment]
Hi Ethan,

This is the same question as raised in #14.

The definition is correct. I think where the confusion lies is when you try to think "I want to vertically align two views". Once you understand how these axes are defined ("a vertical line through the center of the view") it is quite easy to use.

**Comment by zhjuncai** [comment]
Yes, you are right, thanks very much for your link, I think I understand it better. BTW, great work, I change all my auto layout by using your category. thanks a lot
