### ISSUE TITLE
CocoaPods Conflict. Installs different AutoLayout

### ISSUE THREAD

**Issue by objectmethod** [smileyborg/UIView-AutoLayout#4]
There is another UIView+AutoLayout category in CocoaPods that gets installed instead of yours :)

**Comment by smileyborg** [comment]
I just tested on my machine and it's working fine.

```
pod 'UIView+AutoLayout'
```

will install this project.

```
pod 'UIView-Autolayout'
```

will install @jrturton's [project](https://github.com/jrturton/UIView-Autolayout).

Note the difference in the +/- and capitalization of the L.

**Comment by objectmethod** [comment]
You're right. My bad! :)  thanks
