### ISSUE TITLE
Read me attribution

### ISSUE THREAD

**Issue by jrturton** [smileyborg/UIView-AutoLayout#5]
I'm not sure who Tyler Fox is, but you originally forked this from my repository (the link is correct!). My name is Rich Turton, could you correct the read me please?

**Comment by smileyborg** [comment]
Tyler Fox would be me :) Let me re-word it and include you by name to clarify!

**Comment by jrturton** [comment]
The curse of usernames! I see now, you mean it was forked by you as opposed
to the original repo written by you.

On 5 Oct 2013, at 08:17, Tyler Fox notifications@github.com wrote:

Tyler Fox would be me :) Let me re-word it and include you by name to
clarify!

—
Reply to this email directly or view it on
GitHubhttps://github.com/smileyborg/UIView-AutoLayout/issues/5#issuecomment-25743596
.

**Comment by smileyborg** [comment]
Correct. I updated the Credits section -- hopefully more clear now!

**Comment by jrturton** [comment]
Thankyou!
