### ISSUE TITLE
Animating constraints

### ISSUE THREAD

**Issue by bredfield** [smileyborg/UIView-AutoLayout#8]
Once I set up constraints using UIView+Autolayout, what's the preferred method of animating a specific constraint?

**Comment by smileyborg** [comment]
Constraints that you set up using UIView+AutoLayout are identical to constraints you might set up using VFL or by calling the NSLayoutConstraint API directly.

That means you animate constraint changes (after making the changes to the constraints) by calling `[view layoutIfNeeded]` from an animation block.

There's plenty more info on this topic here: http://stackoverflow.com/questions/12926566/are-nslayoutconstraints-animatable

Now, if you're asking how to change multiple constraints but only animate one of them (applying the other changes immediately), that's actually something I haven't tried myself. What I would suggest is this:

```
// First, make all of your constraint changes that you don't want to animate here

[view layoutIfNeeded]; // this will instantly apply the above changes

// Now, make the change to the one constraint you wish to animate

[UIView animateWithDuration:0.2 animations:^{ 
    [view layoutIfNeeded]; // this will animate the one constraint
}];
```

Let me know if that works for you.

**Comment by bredfield** [comment]
Thanks for the quick response! I'm familiar with animating constraints, my problem is figuring out how to reference a single constraint after setting it up with the category method. Typically with the NSLayoutConstraint I would save a reference to an individual one after creating it.

Here's what I have: `
[self.savePopupView autoPinEdgeToSuperviewEdge:ALEdgeTop withInset:100.0]
` 
How would I reference the top-pin to alter the constant? I appreciate the help, sorry if this is off-topic for an issue!

**Comment by smileyborg** [comment]
Oh, now I see what you're asking :)

The answer is incredibly simple: each of the UIView+AutoLayout API methods that creates constraints has a return value. All these methods will create the constraints, add them to the appropriate view, and then return the constraint (or if there are multiple, an NSArray of constraints) to you.

So, in your case, all you need to do is:
`NSLayoutConstraint *constraint = [self.savePopupView autoPinEdgeToSuperviewEdge:ALEdgeTop withInset:100.0];`

You can of course assign that to a property instead, or whatever you like!

**Comment by bredfield** [comment]
Ah, that makes sense. I Should have looked at the fact that the methods return the raw constraint(s). Thanks!

**Comment by nikitaUnii** [comment]
doing this gives me error:

Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "NSLayoutConstraint:0x167b5320 MySubView:0x167c8ef0.bottom == UIView:0x17834820.bottom",
    "NSLayoutConstraint:0x17a0cca0 MySubView:0x167c8ef0.bottom == UIView:0x17834820.bottom - 224"
)

Will attempt to recover by breaking constraint 
NSLayoutConstraint:0x167b5320 MySubView:0x167c8ef0.bottom == UIView:0x17834820.bottom


I receive this error only the first time though.
How do I solve this. Please help!
