### ISSUE TITLE
Support for indirectly derived classes of UIView

### ISSUE THREAD

**Issue by mdrx-io** [smileyborg/UIView-AutoLayout#9]
Perhaps this isn't within the scope of the API, but I was hoping that certain classes such as UITextView would work out of the box. For example, in the TableViewCellWithAutoLayout sample project: when I tried switching the class of bodyLabel to UITextView and commenting out the UILabel-specific properties, the view was missing at runtime.

UITextField works, though - so that's awesome.

**Comment by smileyborg** [comment]
By missing, I assume you mean not visible?

Any subview of UIView should work with this API unless it implements specific behavior that makes it generally incompatible with Auto Layout. (Now, UIScrollView, which UITextView inherits from, does have some important considerations to use with Auto Layout -- but that's when positioning/constraining subviews _within_ the scroll view, not positioning the scroll view itself.)

Can you perhaps share a fork of the example project on GitHub so I can see what you are trying that doesn't work?
